version: "3.7"

services:
  algo:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    volumes:
      - ./data:/app/data
    image: ghcr.io/mosesmc52/futures-trend:${TAG:-latest}
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
